name: Issue report
description: File a issue report for the application.
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report!

        In order to standardize the Issues, we appreciate if you
        fill all the fields in this form using the **English** language.
  - type: input
    id: version
    attributes:
      label: Application version
      description: |
        You can find the version in the dashboard footer when signed in.
      placeholder: |
        Ex. v0.2.28
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: Provide an example of the issue.
      placeholder: |
        Ex.
          1. First step
          2. Second step
          3. Issue here
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      placeholder: |
        Ex. "This should happen..."
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      placeholder: |
        Ex. "This happened instead..."
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Others
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: |
        **Read this carefully**, we will close and ignore your issue if you skimmed through this.
      options:
        - label: I have searched the existing issues and this is not a duplicate.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: I am using the most recent version of the application (`v0.2.28`).
          required: true
        - label: I filled out all the requested information in this form.
          required: true
